# Generated by Django 4.2.9 on 2024-04-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_id", models.IntegerField(default=0)),
                ("player", models.TextField()),
                ("result", models.BooleanField(default=False)),
            ],
        ),
    ]
