# Generated by Django 4.2.9 on 2024-04-05 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="match",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
