# Generated by Django 4.2.9 on 2024-04-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0003_rename_result_match_draw_match_loss_match_win"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("match_id", models.IntegerField(default=0)),
                ("team1", models.BooleanField(default=False)),
                ("draw", models.BooleanField(default=False)),
                ("team2", models.BooleanField(default=False)),
            ],
        ),
    ]
