# Generated by Django 4.2.9 on 2024-04-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0004_matchresult"),
    ]

    operations = [
        migrations.DeleteModel(name="MatchResult",),
        migrations.AddField(
            model_name="match",
            name="team_id",
            field=models.BooleanField(default=False),
        ),
    ]
