# Generated by Django 4.2.9 on 2024-04-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0007_stats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stats",
            name="fraction",
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
